#if .jpg is put into repository, it will be moved to the images folder

name: JPGMover


on:
 
  push:
    paths:
      - '**.jpg'

  pull_request:
    paths:
     - '**.jpg'
    

  workflow_dispatch:


jobs:
  move-jpg:
  
     
    runs-on: ubuntu-latest

   
    steps:
    
      - uses: actions/checkout@v3

      - name: Move all jpg files
        run: mv *.jpg Images

      - name: Commit our changes
        run: |
           git config user.name 'rosst777'
           git config user.email 'teresa.ross@hotmail.com'
           git add . 
           git commit -m "JPG Mover activated"
           git push
